name: CI

on:
  pull_request:
  push:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages (platform 34, build-tools 34.0.0)
        shell: bash
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Assemble Debug
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :app:assembleDebug --no-daemon

      - name: Unit tests (debug)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :app:testDebugUnitTest --no-daemon

      - name: Lint (debug)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :app:lintDebug --no-daemon

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: app/build/test-results/testDebugUnitTest/**/*.xml
          if-no-files-found: ignore

      - name: Upload lint HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report-debug
          path: app/build/reports/lint-results-debug.html
          if-no-files-found: ignore

      - name: Upload debug APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: ignore
